package com.greendao.manager;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xzkydz.greendao.bean.MotorEnity;
import com.xzkydz.greendao.bean.TaskEnity;
import com.xzkydz.greendao.bean.TaskResEnity;

import com.greendao.manager.MotorEnityDao;
import com.greendao.manager.TaskEnityDao;
import com.greendao.manager.TaskResEnityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig motorEnityDaoConfig;
    private final DaoConfig taskEnityDaoConfig;
    private final DaoConfig taskResEnityDaoConfig;

    private final MotorEnityDao motorEnityDao;
    private final TaskEnityDao taskEnityDao;
    private final TaskResEnityDao taskResEnityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        motorEnityDaoConfig = daoConfigMap.get(MotorEnityDao.class).clone();
        motorEnityDaoConfig.initIdentityScope(type);

        taskEnityDaoConfig = daoConfigMap.get(TaskEnityDao.class).clone();
        taskEnityDaoConfig.initIdentityScope(type);

        taskResEnityDaoConfig = daoConfigMap.get(TaskResEnityDao.class).clone();
        taskResEnityDaoConfig.initIdentityScope(type);

        motorEnityDao = new MotorEnityDao(motorEnityDaoConfig, this);
        taskEnityDao = new TaskEnityDao(taskEnityDaoConfig, this);
        taskResEnityDao = new TaskResEnityDao(taskResEnityDaoConfig, this);

        registerDao(MotorEnity.class, motorEnityDao);
        registerDao(TaskEnity.class, taskEnityDao);
        registerDao(TaskResEnity.class, taskResEnityDao);
    }
    
    public void clear() {
        motorEnityDaoConfig.clearIdentityScope();
        taskEnityDaoConfig.clearIdentityScope();
        taskResEnityDaoConfig.clearIdentityScope();
    }

    public MotorEnityDao getMotorEnityDao() {
        return motorEnityDao;
    }

    public TaskEnityDao getTaskEnityDao() {
        return taskEnityDao;
    }

    public TaskResEnityDao getTaskResEnityDao() {
        return taskResEnityDao;
    }

}
