package com.greendao.manager;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.xzkydz.greendao.bean.TaskResEnity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TASK_RES_ENITY".
*/
public class TaskResEnityDao extends AbstractDao<TaskResEnity, Long> {

    public static final String TABLENAME = "TASK_RES_ENITY";

    /**
     * Properties of entity TaskResEnity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property TaskId = new Property(1, long.class, "taskId", false, "TASK_ID");
        public final static Property WdStr = new Property(2, String.class, "wdStr", false, "WD_STR");
        public final static Property SdStr = new Property(3, String.class, "sdStr", false, "SD_STR");
        public final static Property DqyStr = new Property(4, String.class, "dqyStr", false, "DQY_STR");
        public final static Property TimeStr = new Property(5, String.class, "timeStr", false, "TIME_STR");
        public final static Property TestFunctionStr = new Property(6, String.class, "testFunctionStr", false, "TEST_FUNCTION_STR");
        public final static Property AbV = new Property(7, String.class, "abV", false, "AB_V");
        public final static Property AA = new Property(8, String.class, "aA", false, "A_A");
        public final static Property BcV = new Property(9, String.class, "bcV", false, "BC_V");
        public final static Property BA = new Property(10, String.class, "bA", false, "B_A");
        public final static Property CaV = new Property(11, String.class, "caV", false, "CA_V");
        public final static Property CA = new Property(12, String.class, "cA", false, "C_A");
        public final static Property PjV = new Property(13, String.class, "pjV", false, "PJ_V");
        public final static Property PjA = new Property(14, String.class, "pjA", false, "PJ_A");
        public final static Property Djgl = new Property(15, String.class, "djgl", false, "DJGL");
        public final static Property Zgl = new Property(16, String.class, "zgl", false, "ZGL");
        public final static Property Scgl = new Property(17, String.class, "scgl", false, "SCGL");
        public final static Property Djxl = new Property(18, String.class, "djxl", false, "DJXL");
        public final static Property Zhxl = new Property(19, String.class, "zhxl", false, "ZHXL");
        public final static Property Glys = new Property(20, String.class, "glys", false, "GLYS");
        public final static Property Fzxs = new Property(21, String.class, "fzxs", false, "FZXS");
        public final static Property Yxzt = new Property(22, String.class, "yxzt", false, "YXZT");
        public final static Property Ll_PTG = new Property(23, String.class, "ll_PTG", false, "LL__PTG");
        public final static Property Eyht_PTG = new Property(24, String.class, "eyht_PTG", false, "EYHT__PTG");
        public final static Property Yyht_PTG = new Property(25, String.class, "yyht_PTG", false, "YYHT__PTG");
        public final static Property Yq_PTG = new Property(26, String.class, "yq_PTG", false, "YQ__PTG");
        public final static Property Jw_PTG = new Property(27, String.class, "jw_PTG", false, "JW__PTG");
        public final static Property Dqy_PTG = new Property(28, String.class, "dqy_PTG", false, "DQY__PTG");
        public final static Property Jkjy_PTG = new Property(29, String.class, "jkjy_PTG", false, "JKJY__PTG");
        public final static Property Ckjy_PTG = new Property(30, String.class, "ckjy_PTG", false, "CKJY__PTG");
        public final static Property Gdfy_PTG = new Property(31, String.class, "gdfy_PTG", false, "GDFY__PTG");
        public final static Property Gdjy_PTG = new Property(32, String.class, "gdjy_PTG", false, "GDJY__PTG");
        public final static Property Gdcy_PTG = new Property(33, String.class, "gdcy_PTG", false, "GDCY__PTG");
        public final static Property Zs_PTG = new Property(34, String.class, "zs_PTG", false, "ZS__PTG");
        public final static Property Qtwd_PTG = new Property(35, String.class, "qtwd_PTG", false, "QTWD__PTG");
        public final static Property LlQGDTJ_PTG = new Property(36, String.class, "llQGDTJ_PTG", false, "LL_QGDTJ__PTG");
        public final static Property LlBGDTJ_PTG = new Property(37, String.class, "llBGDTJ_PTG", false, "LL_BGDTJ__PTG");
        public final static Property ZglBGDTJ_PTG = new Property(38, String.class, "zglBGDTJ_PTG", false, "ZGL_BGDTJ__PTG");
        public final static Property JxzkdBGDTJ_PTG = new Property(39, String.class, "jxzkdBGDTJ_PTG", false, "JXZKD_BGDTJ__PTG");
        public final static Property JkjyBCS_KB = new Property(40, String.class, "jkjyBCS_KB", false, "JKJY_BCS__KB");
        public final static Property CkjyBCS_KB = new Property(41, String.class, "ckjyBCS_KB", false, "CKJY_BCS__KB");
        public final static Property ZsBCS_KB = new Property(42, String.class, "zsBCS_KB", false, "ZS_BCS__KB");
        public final static Property JswdBCS_KB = new Property(43, String.class, "jswdBCS_KB", false, "JSWD_BCS__KB");
        public final static Property Gdfy_KBVZh = new Property(44, String.class, "gdfy_KBVZh", false, "GDFY__KBVZH");
        public final static Property Gdjy_KBVZh = new Property(45, String.class, "gdjy_KBVZh", false, "GDJY__KBVZH");
        public final static Property Gdcy_KBVZh = new Property(46, String.class, "gdcy_KBVZh", false, "GDCY__KBVZH");
        public final static Property Dqy_KBVZh = new Property(47, String.class, "dqy_KBVZh", false, "DQY__KBVZH");
        public final static Property Ll_KBVZh = new Property(48, String.class, "ll_KBVZh", false, "LL__KBVZH");
        public final static Property Jw_KBVZh = new Property(49, String.class, "jw_KBVZh", false, "JW__KBVZH");
        public final static Property Eyht_KBVZh = new Property(50, String.class, "eyht_KBVZh", false, "EYHT__KBVZH");
        public final static Property Yyht_KBVZh = new Property(51, String.class, "yyht_KBVZh", false, "YYHT__KBVZH");
        public final static Property Yq_KBVZh = new Property(52, String.class, "yq_KBVZh", false, "YQ__KBVZH");
        public final static Property Qtwd_KBVZh = new Property(53, String.class, "qtwd_KBVZh", false, "QTWD__KBVZH");
        public final static Property LlQGDTJ_KBVZh = new Property(54, String.class, "llQGDTJ_KBVZh", false, "LL_QGDTJ__KBVZH");
        public final static Property LlBGDTJ_KBVZh = new Property(55, String.class, "llBGDTJ_KBVZh", false, "LL_BGDTJ__KBVZH");
        public final static Property ZglBGDTJ_KBVZh = new Property(56, String.class, "zglBGDTJ_KBVZh", false, "ZGL_BGDTJ__KBVZH");
        public final static Property JxzkdBGDTJ_KBVZh = new Property(57, String.class, "jxzkdBGDTJ_KBVZh", false, "JXZKD_BGDTJ__KBVZH");
        public final static Property Eyht_ZHGL = new Property(58, String.class, "eyht_ZHGL", false, "EYHT__ZHGL");
        public final static Property Yyht_ZHGL = new Property(59, String.class, "yyht_ZHGL", false, "YYHT__ZHGL");
        public final static Property Yq_ZHGL = new Property(60, String.class, "yq_ZHGL", false, "YQ__ZHGL");
        public final static Property Jw_ZHGL = new Property(61, String.class, "jw_ZHGL", false, "JW__ZHGL");
        public final static Property Gdfy_ZHGL = new Property(62, String.class, "gdfy_ZHGL", false, "GDFY__ZHGL");
        public final static Property Gdjy_ZHGL = new Property(63, String.class, "gdjy_ZHGL", false, "GDJY__ZHGL");
        public final static Property Gdcy_ZHGL = new Property(64, String.class, "gdcy_ZHGL", false, "GDCY__ZHGL");
        public final static Property Ll_ZHGL = new Property(65, String.class, "ll_ZHGL", false, "LL__ZHGL");
        public final static Property Qtwd_ZHGL = new Property(66, String.class, "qtwd_ZHGL", false, "QTWD__ZHGL");
    }


    public TaskResEnityDao(DaoConfig config) {
        super(config);
    }
    
    public TaskResEnityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TASK_RES_ENITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TASK_ID\" INTEGER NOT NULL ," + // 1: taskId
                "\"WD_STR\" TEXT," + // 2: wdStr
                "\"SD_STR\" TEXT," + // 3: sdStr
                "\"DQY_STR\" TEXT," + // 4: dqyStr
                "\"TIME_STR\" TEXT," + // 5: timeStr
                "\"TEST_FUNCTION_STR\" TEXT," + // 6: testFunctionStr
                "\"AB_V\" TEXT UNIQUE ," + // 7: abV
                "\"A_A\" TEXT," + // 8: aA
                "\"BC_V\" TEXT," + // 9: bcV
                "\"B_A\" TEXT," + // 10: bA
                "\"CA_V\" TEXT," + // 11: caV
                "\"C_A\" TEXT," + // 12: cA
                "\"PJ_V\" TEXT," + // 13: pjV
                "\"PJ_A\" TEXT," + // 14: pjA
                "\"DJGL\" TEXT," + // 15: djgl
                "\"ZGL\" TEXT," + // 16: zgl
                "\"SCGL\" TEXT," + // 17: scgl
                "\"DJXL\" TEXT," + // 18: djxl
                "\"ZHXL\" TEXT," + // 19: zhxl
                "\"GLYS\" TEXT," + // 20: glys
                "\"FZXS\" TEXT," + // 21: fzxs
                "\"YXZT\" TEXT," + // 22: yxzt
                "\"LL__PTG\" TEXT," + // 23: ll_PTG
                "\"EYHT__PTG\" TEXT," + // 24: eyht_PTG
                "\"YYHT__PTG\" TEXT," + // 25: yyht_PTG
                "\"YQ__PTG\" TEXT," + // 26: yq_PTG
                "\"JW__PTG\" TEXT," + // 27: jw_PTG
                "\"DQY__PTG\" TEXT," + // 28: dqy_PTG
                "\"JKJY__PTG\" TEXT," + // 29: jkjy_PTG
                "\"CKJY__PTG\" TEXT," + // 30: ckjy_PTG
                "\"GDFY__PTG\" TEXT," + // 31: gdfy_PTG
                "\"GDJY__PTG\" TEXT," + // 32: gdjy_PTG
                "\"GDCY__PTG\" TEXT," + // 33: gdcy_PTG
                "\"ZS__PTG\" TEXT," + // 34: zs_PTG
                "\"QTWD__PTG\" TEXT," + // 35: qtwd_PTG
                "\"LL_QGDTJ__PTG\" TEXT," + // 36: llQGDTJ_PTG
                "\"LL_BGDTJ__PTG\" TEXT," + // 37: llBGDTJ_PTG
                "\"ZGL_BGDTJ__PTG\" TEXT," + // 38: zglBGDTJ_PTG
                "\"JXZKD_BGDTJ__PTG\" TEXT," + // 39: jxzkdBGDTJ_PTG
                "\"JKJY_BCS__KB\" TEXT," + // 40: jkjyBCS_KB
                "\"CKJY_BCS__KB\" TEXT," + // 41: ckjyBCS_KB
                "\"ZS_BCS__KB\" TEXT," + // 42: zsBCS_KB
                "\"JSWD_BCS__KB\" TEXT," + // 43: jswdBCS_KB
                "\"GDFY__KBVZH\" TEXT," + // 44: gdfy_KBVZh
                "\"GDJY__KBVZH\" TEXT," + // 45: gdjy_KBVZh
                "\"GDCY__KBVZH\" TEXT," + // 46: gdcy_KBVZh
                "\"DQY__KBVZH\" TEXT," + // 47: dqy_KBVZh
                "\"LL__KBVZH\" TEXT," + // 48: ll_KBVZh
                "\"JW__KBVZH\" TEXT," + // 49: jw_KBVZh
                "\"EYHT__KBVZH\" TEXT," + // 50: eyht_KBVZh
                "\"YYHT__KBVZH\" TEXT," + // 51: yyht_KBVZh
                "\"YQ__KBVZH\" TEXT," + // 52: yq_KBVZh
                "\"QTWD__KBVZH\" TEXT," + // 53: qtwd_KBVZh
                "\"LL_QGDTJ__KBVZH\" TEXT," + // 54: llQGDTJ_KBVZh
                "\"LL_BGDTJ__KBVZH\" TEXT," + // 55: llBGDTJ_KBVZh
                "\"ZGL_BGDTJ__KBVZH\" TEXT," + // 56: zglBGDTJ_KBVZh
                "\"JXZKD_BGDTJ__KBVZH\" TEXT," + // 57: jxzkdBGDTJ_KBVZh
                "\"EYHT__ZHGL\" TEXT," + // 58: eyht_ZHGL
                "\"YYHT__ZHGL\" TEXT," + // 59: yyht_ZHGL
                "\"YQ__ZHGL\" TEXT," + // 60: yq_ZHGL
                "\"JW__ZHGL\" TEXT," + // 61: jw_ZHGL
                "\"GDFY__ZHGL\" TEXT," + // 62: gdfy_ZHGL
                "\"GDJY__ZHGL\" TEXT," + // 63: gdjy_ZHGL
                "\"GDCY__ZHGL\" TEXT," + // 64: gdcy_ZHGL
                "\"LL__ZHGL\" TEXT," + // 65: ll_ZHGL
                "\"QTWD__ZHGL\" TEXT);"); // 66: qtwd_ZHGL
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TASK_RES_ENITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TaskResEnity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getTaskId());
 
        String wdStr = entity.getWdStr();
        if (wdStr != null) {
            stmt.bindString(3, wdStr);
        }
 
        String sdStr = entity.getSdStr();
        if (sdStr != null) {
            stmt.bindString(4, sdStr);
        }
 
        String dqyStr = entity.getDqyStr();
        if (dqyStr != null) {
            stmt.bindString(5, dqyStr);
        }
 
        String timeStr = entity.getTimeStr();
        if (timeStr != null) {
            stmt.bindString(6, timeStr);
        }
 
        String testFunctionStr = entity.getTestFunctionStr();
        if (testFunctionStr != null) {
            stmt.bindString(7, testFunctionStr);
        }
 
        String abV = entity.getAbV();
        if (abV != null) {
            stmt.bindString(8, abV);
        }
 
        String aA = entity.getAA();
        if (aA != null) {
            stmt.bindString(9, aA);
        }
 
        String bcV = entity.getBcV();
        if (bcV != null) {
            stmt.bindString(10, bcV);
        }
 
        String bA = entity.getBA();
        if (bA != null) {
            stmt.bindString(11, bA);
        }
 
        String caV = entity.getCaV();
        if (caV != null) {
            stmt.bindString(12, caV);
        }
 
        String cA = entity.getCA();
        if (cA != null) {
            stmt.bindString(13, cA);
        }
 
        String pjV = entity.getPjV();
        if (pjV != null) {
            stmt.bindString(14, pjV);
        }
 
        String pjA = entity.getPjA();
        if (pjA != null) {
            stmt.bindString(15, pjA);
        }
 
        String djgl = entity.getDjgl();
        if (djgl != null) {
            stmt.bindString(16, djgl);
        }
 
        String zgl = entity.getZgl();
        if (zgl != null) {
            stmt.bindString(17, zgl);
        }
 
        String scgl = entity.getScgl();
        if (scgl != null) {
            stmt.bindString(18, scgl);
        }
 
        String djxl = entity.getDjxl();
        if (djxl != null) {
            stmt.bindString(19, djxl);
        }
 
        String zhxl = entity.getZhxl();
        if (zhxl != null) {
            stmt.bindString(20, zhxl);
        }
 
        String glys = entity.getGlys();
        if (glys != null) {
            stmt.bindString(21, glys);
        }
 
        String fzxs = entity.getFzxs();
        if (fzxs != null) {
            stmt.bindString(22, fzxs);
        }
 
        String yxzt = entity.getYxzt();
        if (yxzt != null) {
            stmt.bindString(23, yxzt);
        }
 
        String ll_PTG = entity.getLl_PTG();
        if (ll_PTG != null) {
            stmt.bindString(24, ll_PTG);
        }
 
        String eyht_PTG = entity.getEyht_PTG();
        if (eyht_PTG != null) {
            stmt.bindString(25, eyht_PTG);
        }
 
        String yyht_PTG = entity.getYyht_PTG();
        if (yyht_PTG != null) {
            stmt.bindString(26, yyht_PTG);
        }
 
        String yq_PTG = entity.getYq_PTG();
        if (yq_PTG != null) {
            stmt.bindString(27, yq_PTG);
        }
 
        String jw_PTG = entity.getJw_PTG();
        if (jw_PTG != null) {
            stmt.bindString(28, jw_PTG);
        }
 
        String dqy_PTG = entity.getDqy_PTG();
        if (dqy_PTG != null) {
            stmt.bindString(29, dqy_PTG);
        }
 
        String jkjy_PTG = entity.getJkjy_PTG();
        if (jkjy_PTG != null) {
            stmt.bindString(30, jkjy_PTG);
        }
 
        String ckjy_PTG = entity.getCkjy_PTG();
        if (ckjy_PTG != null) {
            stmt.bindString(31, ckjy_PTG);
        }
 
        String gdfy_PTG = entity.getGdfy_PTG();
        if (gdfy_PTG != null) {
            stmt.bindString(32, gdfy_PTG);
        }
 
        String gdjy_PTG = entity.getGdjy_PTG();
        if (gdjy_PTG != null) {
            stmt.bindString(33, gdjy_PTG);
        }
 
        String gdcy_PTG = entity.getGdcy_PTG();
        if (gdcy_PTG != null) {
            stmt.bindString(34, gdcy_PTG);
        }
 
        String zs_PTG = entity.getZs_PTG();
        if (zs_PTG != null) {
            stmt.bindString(35, zs_PTG);
        }
 
        String qtwd_PTG = entity.getQtwd_PTG();
        if (qtwd_PTG != null) {
            stmt.bindString(36, qtwd_PTG);
        }
 
        String llQGDTJ_PTG = entity.getLlQGDTJ_PTG();
        if (llQGDTJ_PTG != null) {
            stmt.bindString(37, llQGDTJ_PTG);
        }
 
        String llBGDTJ_PTG = entity.getLlBGDTJ_PTG();
        if (llBGDTJ_PTG != null) {
            stmt.bindString(38, llBGDTJ_PTG);
        }
 
        String zglBGDTJ_PTG = entity.getZglBGDTJ_PTG();
        if (zglBGDTJ_PTG != null) {
            stmt.bindString(39, zglBGDTJ_PTG);
        }
 
        String jxzkdBGDTJ_PTG = entity.getJxzkdBGDTJ_PTG();
        if (jxzkdBGDTJ_PTG != null) {
            stmt.bindString(40, jxzkdBGDTJ_PTG);
        }
 
        String jkjyBCS_KB = entity.getJkjyBCS_KB();
        if (jkjyBCS_KB != null) {
            stmt.bindString(41, jkjyBCS_KB);
        }
 
        String ckjyBCS_KB = entity.getCkjyBCS_KB();
        if (ckjyBCS_KB != null) {
            stmt.bindString(42, ckjyBCS_KB);
        }
 
        String zsBCS_KB = entity.getZsBCS_KB();
        if (zsBCS_KB != null) {
            stmt.bindString(43, zsBCS_KB);
        }
 
        String jswdBCS_KB = entity.getJswdBCS_KB();
        if (jswdBCS_KB != null) {
            stmt.bindString(44, jswdBCS_KB);
        }
 
        String gdfy_KBVZh = entity.getGdfy_KBVZh();
        if (gdfy_KBVZh != null) {
            stmt.bindString(45, gdfy_KBVZh);
        }
 
        String gdjy_KBVZh = entity.getGdjy_KBVZh();
        if (gdjy_KBVZh != null) {
            stmt.bindString(46, gdjy_KBVZh);
        }
 
        String gdcy_KBVZh = entity.getGdcy_KBVZh();
        if (gdcy_KBVZh != null) {
            stmt.bindString(47, gdcy_KBVZh);
        }
 
        String dqy_KBVZh = entity.getDqy_KBVZh();
        if (dqy_KBVZh != null) {
            stmt.bindString(48, dqy_KBVZh);
        }
 
        String ll_KBVZh = entity.getLl_KBVZh();
        if (ll_KBVZh != null) {
            stmt.bindString(49, ll_KBVZh);
        }
 
        String jw_KBVZh = entity.getJw_KBVZh();
        if (jw_KBVZh != null) {
            stmt.bindString(50, jw_KBVZh);
        }
 
        String eyht_KBVZh = entity.getEyht_KBVZh();
        if (eyht_KBVZh != null) {
            stmt.bindString(51, eyht_KBVZh);
        }
 
        String yyht_KBVZh = entity.getYyht_KBVZh();
        if (yyht_KBVZh != null) {
            stmt.bindString(52, yyht_KBVZh);
        }
 
        String yq_KBVZh = entity.getYq_KBVZh();
        if (yq_KBVZh != null) {
            stmt.bindString(53, yq_KBVZh);
        }
 
        String qtwd_KBVZh = entity.getQtwd_KBVZh();
        if (qtwd_KBVZh != null) {
            stmt.bindString(54, qtwd_KBVZh);
        }
 
        String llQGDTJ_KBVZh = entity.getLlQGDTJ_KBVZh();
        if (llQGDTJ_KBVZh != null) {
            stmt.bindString(55, llQGDTJ_KBVZh);
        }
 
        String llBGDTJ_KBVZh = entity.getLlBGDTJ_KBVZh();
        if (llBGDTJ_KBVZh != null) {
            stmt.bindString(56, llBGDTJ_KBVZh);
        }
 
        String zglBGDTJ_KBVZh = entity.getZglBGDTJ_KBVZh();
        if (zglBGDTJ_KBVZh != null) {
            stmt.bindString(57, zglBGDTJ_KBVZh);
        }
 
        String jxzkdBGDTJ_KBVZh = entity.getJxzkdBGDTJ_KBVZh();
        if (jxzkdBGDTJ_KBVZh != null) {
            stmt.bindString(58, jxzkdBGDTJ_KBVZh);
        }
 
        String eyht_ZHGL = entity.getEyht_ZHGL();
        if (eyht_ZHGL != null) {
            stmt.bindString(59, eyht_ZHGL);
        }
 
        String yyht_ZHGL = entity.getYyht_ZHGL();
        if (yyht_ZHGL != null) {
            stmt.bindString(60, yyht_ZHGL);
        }
 
        String yq_ZHGL = entity.getYq_ZHGL();
        if (yq_ZHGL != null) {
            stmt.bindString(61, yq_ZHGL);
        }
 
        String jw_ZHGL = entity.getJw_ZHGL();
        if (jw_ZHGL != null) {
            stmt.bindString(62, jw_ZHGL);
        }
 
        String gdfy_ZHGL = entity.getGdfy_ZHGL();
        if (gdfy_ZHGL != null) {
            stmt.bindString(63, gdfy_ZHGL);
        }
 
        String gdjy_ZHGL = entity.getGdjy_ZHGL();
        if (gdjy_ZHGL != null) {
            stmt.bindString(64, gdjy_ZHGL);
        }
 
        String gdcy_ZHGL = entity.getGdcy_ZHGL();
        if (gdcy_ZHGL != null) {
            stmt.bindString(65, gdcy_ZHGL);
        }
 
        String ll_ZHGL = entity.getLl_ZHGL();
        if (ll_ZHGL != null) {
            stmt.bindString(66, ll_ZHGL);
        }
 
        String qtwd_ZHGL = entity.getQtwd_ZHGL();
        if (qtwd_ZHGL != null) {
            stmt.bindString(67, qtwd_ZHGL);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TaskResEnity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getTaskId());
 
        String wdStr = entity.getWdStr();
        if (wdStr != null) {
            stmt.bindString(3, wdStr);
        }
 
        String sdStr = entity.getSdStr();
        if (sdStr != null) {
            stmt.bindString(4, sdStr);
        }
 
        String dqyStr = entity.getDqyStr();
        if (dqyStr != null) {
            stmt.bindString(5, dqyStr);
        }
 
        String timeStr = entity.getTimeStr();
        if (timeStr != null) {
            stmt.bindString(6, timeStr);
        }
 
        String testFunctionStr = entity.getTestFunctionStr();
        if (testFunctionStr != null) {
            stmt.bindString(7, testFunctionStr);
        }
 
        String abV = entity.getAbV();
        if (abV != null) {
            stmt.bindString(8, abV);
        }
 
        String aA = entity.getAA();
        if (aA != null) {
            stmt.bindString(9, aA);
        }
 
        String bcV = entity.getBcV();
        if (bcV != null) {
            stmt.bindString(10, bcV);
        }
 
        String bA = entity.getBA();
        if (bA != null) {
            stmt.bindString(11, bA);
        }
 
        String caV = entity.getCaV();
        if (caV != null) {
            stmt.bindString(12, caV);
        }
 
        String cA = entity.getCA();
        if (cA != null) {
            stmt.bindString(13, cA);
        }
 
        String pjV = entity.getPjV();
        if (pjV != null) {
            stmt.bindString(14, pjV);
        }
 
        String pjA = entity.getPjA();
        if (pjA != null) {
            stmt.bindString(15, pjA);
        }
 
        String djgl = entity.getDjgl();
        if (djgl != null) {
            stmt.bindString(16, djgl);
        }
 
        String zgl = entity.getZgl();
        if (zgl != null) {
            stmt.bindString(17, zgl);
        }
 
        String scgl = entity.getScgl();
        if (scgl != null) {
            stmt.bindString(18, scgl);
        }
 
        String djxl = entity.getDjxl();
        if (djxl != null) {
            stmt.bindString(19, djxl);
        }
 
        String zhxl = entity.getZhxl();
        if (zhxl != null) {
            stmt.bindString(20, zhxl);
        }
 
        String glys = entity.getGlys();
        if (glys != null) {
            stmt.bindString(21, glys);
        }
 
        String fzxs = entity.getFzxs();
        if (fzxs != null) {
            stmt.bindString(22, fzxs);
        }
 
        String yxzt = entity.getYxzt();
        if (yxzt != null) {
            stmt.bindString(23, yxzt);
        }
 
        String ll_PTG = entity.getLl_PTG();
        if (ll_PTG != null) {
            stmt.bindString(24, ll_PTG);
        }
 
        String eyht_PTG = entity.getEyht_PTG();
        if (eyht_PTG != null) {
            stmt.bindString(25, eyht_PTG);
        }
 
        String yyht_PTG = entity.getYyht_PTG();
        if (yyht_PTG != null) {
            stmt.bindString(26, yyht_PTG);
        }
 
        String yq_PTG = entity.getYq_PTG();
        if (yq_PTG != null) {
            stmt.bindString(27, yq_PTG);
        }
 
        String jw_PTG = entity.getJw_PTG();
        if (jw_PTG != null) {
            stmt.bindString(28, jw_PTG);
        }
 
        String dqy_PTG = entity.getDqy_PTG();
        if (dqy_PTG != null) {
            stmt.bindString(29, dqy_PTG);
        }
 
        String jkjy_PTG = entity.getJkjy_PTG();
        if (jkjy_PTG != null) {
            stmt.bindString(30, jkjy_PTG);
        }
 
        String ckjy_PTG = entity.getCkjy_PTG();
        if (ckjy_PTG != null) {
            stmt.bindString(31, ckjy_PTG);
        }
 
        String gdfy_PTG = entity.getGdfy_PTG();
        if (gdfy_PTG != null) {
            stmt.bindString(32, gdfy_PTG);
        }
 
        String gdjy_PTG = entity.getGdjy_PTG();
        if (gdjy_PTG != null) {
            stmt.bindString(33, gdjy_PTG);
        }
 
        String gdcy_PTG = entity.getGdcy_PTG();
        if (gdcy_PTG != null) {
            stmt.bindString(34, gdcy_PTG);
        }
 
        String zs_PTG = entity.getZs_PTG();
        if (zs_PTG != null) {
            stmt.bindString(35, zs_PTG);
        }
 
        String qtwd_PTG = entity.getQtwd_PTG();
        if (qtwd_PTG != null) {
            stmt.bindString(36, qtwd_PTG);
        }
 
        String llQGDTJ_PTG = entity.getLlQGDTJ_PTG();
        if (llQGDTJ_PTG != null) {
            stmt.bindString(37, llQGDTJ_PTG);
        }
 
        String llBGDTJ_PTG = entity.getLlBGDTJ_PTG();
        if (llBGDTJ_PTG != null) {
            stmt.bindString(38, llBGDTJ_PTG);
        }
 
        String zglBGDTJ_PTG = entity.getZglBGDTJ_PTG();
        if (zglBGDTJ_PTG != null) {
            stmt.bindString(39, zglBGDTJ_PTG);
        }
 
        String jxzkdBGDTJ_PTG = entity.getJxzkdBGDTJ_PTG();
        if (jxzkdBGDTJ_PTG != null) {
            stmt.bindString(40, jxzkdBGDTJ_PTG);
        }
 
        String jkjyBCS_KB = entity.getJkjyBCS_KB();
        if (jkjyBCS_KB != null) {
            stmt.bindString(41, jkjyBCS_KB);
        }
 
        String ckjyBCS_KB = entity.getCkjyBCS_KB();
        if (ckjyBCS_KB != null) {
            stmt.bindString(42, ckjyBCS_KB);
        }
 
        String zsBCS_KB = entity.getZsBCS_KB();
        if (zsBCS_KB != null) {
            stmt.bindString(43, zsBCS_KB);
        }
 
        String jswdBCS_KB = entity.getJswdBCS_KB();
        if (jswdBCS_KB != null) {
            stmt.bindString(44, jswdBCS_KB);
        }
 
        String gdfy_KBVZh = entity.getGdfy_KBVZh();
        if (gdfy_KBVZh != null) {
            stmt.bindString(45, gdfy_KBVZh);
        }
 
        String gdjy_KBVZh = entity.getGdjy_KBVZh();
        if (gdjy_KBVZh != null) {
            stmt.bindString(46, gdjy_KBVZh);
        }
 
        String gdcy_KBVZh = entity.getGdcy_KBVZh();
        if (gdcy_KBVZh != null) {
            stmt.bindString(47, gdcy_KBVZh);
        }
 
        String dqy_KBVZh = entity.getDqy_KBVZh();
        if (dqy_KBVZh != null) {
            stmt.bindString(48, dqy_KBVZh);
        }
 
        String ll_KBVZh = entity.getLl_KBVZh();
        if (ll_KBVZh != null) {
            stmt.bindString(49, ll_KBVZh);
        }
 
        String jw_KBVZh = entity.getJw_KBVZh();
        if (jw_KBVZh != null) {
            stmt.bindString(50, jw_KBVZh);
        }
 
        String eyht_KBVZh = entity.getEyht_KBVZh();
        if (eyht_KBVZh != null) {
            stmt.bindString(51, eyht_KBVZh);
        }
 
        String yyht_KBVZh = entity.getYyht_KBVZh();
        if (yyht_KBVZh != null) {
            stmt.bindString(52, yyht_KBVZh);
        }
 
        String yq_KBVZh = entity.getYq_KBVZh();
        if (yq_KBVZh != null) {
            stmt.bindString(53, yq_KBVZh);
        }
 
        String qtwd_KBVZh = entity.getQtwd_KBVZh();
        if (qtwd_KBVZh != null) {
            stmt.bindString(54, qtwd_KBVZh);
        }
 
        String llQGDTJ_KBVZh = entity.getLlQGDTJ_KBVZh();
        if (llQGDTJ_KBVZh != null) {
            stmt.bindString(55, llQGDTJ_KBVZh);
        }
 
        String llBGDTJ_KBVZh = entity.getLlBGDTJ_KBVZh();
        if (llBGDTJ_KBVZh != null) {
            stmt.bindString(56, llBGDTJ_KBVZh);
        }
 
        String zglBGDTJ_KBVZh = entity.getZglBGDTJ_KBVZh();
        if (zglBGDTJ_KBVZh != null) {
            stmt.bindString(57, zglBGDTJ_KBVZh);
        }
 
        String jxzkdBGDTJ_KBVZh = entity.getJxzkdBGDTJ_KBVZh();
        if (jxzkdBGDTJ_KBVZh != null) {
            stmt.bindString(58, jxzkdBGDTJ_KBVZh);
        }
 
        String eyht_ZHGL = entity.getEyht_ZHGL();
        if (eyht_ZHGL != null) {
            stmt.bindString(59, eyht_ZHGL);
        }
 
        String yyht_ZHGL = entity.getYyht_ZHGL();
        if (yyht_ZHGL != null) {
            stmt.bindString(60, yyht_ZHGL);
        }
 
        String yq_ZHGL = entity.getYq_ZHGL();
        if (yq_ZHGL != null) {
            stmt.bindString(61, yq_ZHGL);
        }
 
        String jw_ZHGL = entity.getJw_ZHGL();
        if (jw_ZHGL != null) {
            stmt.bindString(62, jw_ZHGL);
        }
 
        String gdfy_ZHGL = entity.getGdfy_ZHGL();
        if (gdfy_ZHGL != null) {
            stmt.bindString(63, gdfy_ZHGL);
        }
 
        String gdjy_ZHGL = entity.getGdjy_ZHGL();
        if (gdjy_ZHGL != null) {
            stmt.bindString(64, gdjy_ZHGL);
        }
 
        String gdcy_ZHGL = entity.getGdcy_ZHGL();
        if (gdcy_ZHGL != null) {
            stmt.bindString(65, gdcy_ZHGL);
        }
 
        String ll_ZHGL = entity.getLl_ZHGL();
        if (ll_ZHGL != null) {
            stmt.bindString(66, ll_ZHGL);
        }
 
        String qtwd_ZHGL = entity.getQtwd_ZHGL();
        if (qtwd_ZHGL != null) {
            stmt.bindString(67, qtwd_ZHGL);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TaskResEnity readEntity(Cursor cursor, int offset) {
        TaskResEnity entity = new TaskResEnity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // taskId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // wdStr
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // sdStr
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // dqyStr
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // timeStr
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // testFunctionStr
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // abV
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // aA
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // bcV
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // bA
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // caV
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // cA
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // pjV
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // pjA
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // djgl
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // zgl
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // scgl
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // djxl
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // zhxl
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // glys
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // fzxs
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // yxzt
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // ll_PTG
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // eyht_PTG
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // yyht_PTG
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // yq_PTG
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // jw_PTG
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // dqy_PTG
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // jkjy_PTG
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // ckjy_PTG
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // gdfy_PTG
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // gdjy_PTG
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // gdcy_PTG
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // zs_PTG
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // qtwd_PTG
            cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36), // llQGDTJ_PTG
            cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37), // llBGDTJ_PTG
            cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38), // zglBGDTJ_PTG
            cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39), // jxzkdBGDTJ_PTG
            cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40), // jkjyBCS_KB
            cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41), // ckjyBCS_KB
            cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42), // zsBCS_KB
            cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43), // jswdBCS_KB
            cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44), // gdfy_KBVZh
            cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45), // gdjy_KBVZh
            cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46), // gdcy_KBVZh
            cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47), // dqy_KBVZh
            cursor.isNull(offset + 48) ? null : cursor.getString(offset + 48), // ll_KBVZh
            cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49), // jw_KBVZh
            cursor.isNull(offset + 50) ? null : cursor.getString(offset + 50), // eyht_KBVZh
            cursor.isNull(offset + 51) ? null : cursor.getString(offset + 51), // yyht_KBVZh
            cursor.isNull(offset + 52) ? null : cursor.getString(offset + 52), // yq_KBVZh
            cursor.isNull(offset + 53) ? null : cursor.getString(offset + 53), // qtwd_KBVZh
            cursor.isNull(offset + 54) ? null : cursor.getString(offset + 54), // llQGDTJ_KBVZh
            cursor.isNull(offset + 55) ? null : cursor.getString(offset + 55), // llBGDTJ_KBVZh
            cursor.isNull(offset + 56) ? null : cursor.getString(offset + 56), // zglBGDTJ_KBVZh
            cursor.isNull(offset + 57) ? null : cursor.getString(offset + 57), // jxzkdBGDTJ_KBVZh
            cursor.isNull(offset + 58) ? null : cursor.getString(offset + 58), // eyht_ZHGL
            cursor.isNull(offset + 59) ? null : cursor.getString(offset + 59), // yyht_ZHGL
            cursor.isNull(offset + 60) ? null : cursor.getString(offset + 60), // yq_ZHGL
            cursor.isNull(offset + 61) ? null : cursor.getString(offset + 61), // jw_ZHGL
            cursor.isNull(offset + 62) ? null : cursor.getString(offset + 62), // gdfy_ZHGL
            cursor.isNull(offset + 63) ? null : cursor.getString(offset + 63), // gdjy_ZHGL
            cursor.isNull(offset + 64) ? null : cursor.getString(offset + 64), // gdcy_ZHGL
            cursor.isNull(offset + 65) ? null : cursor.getString(offset + 65), // ll_ZHGL
            cursor.isNull(offset + 66) ? null : cursor.getString(offset + 66) // qtwd_ZHGL
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TaskResEnity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTaskId(cursor.getLong(offset + 1));
        entity.setWdStr(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSdStr(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDqyStr(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTimeStr(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTestFunctionStr(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setAbV(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setAA(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setBcV(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setBA(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setCaV(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setCA(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setPjV(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setPjA(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setDjgl(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setZgl(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setScgl(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setDjxl(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setZhxl(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setGlys(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setFzxs(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setYxzt(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setLl_PTG(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setEyht_PTG(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setYyht_PTG(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setYq_PTG(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setJw_PTG(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setDqy_PTG(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setJkjy_PTG(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setCkjy_PTG(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setGdfy_PTG(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setGdjy_PTG(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setGdcy_PTG(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setZs_PTG(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setQtwd_PTG(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setLlQGDTJ_PTG(cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36));
        entity.setLlBGDTJ_PTG(cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37));
        entity.setZglBGDTJ_PTG(cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38));
        entity.setJxzkdBGDTJ_PTG(cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39));
        entity.setJkjyBCS_KB(cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40));
        entity.setCkjyBCS_KB(cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41));
        entity.setZsBCS_KB(cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42));
        entity.setJswdBCS_KB(cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43));
        entity.setGdfy_KBVZh(cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44));
        entity.setGdjy_KBVZh(cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45));
        entity.setGdcy_KBVZh(cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46));
        entity.setDqy_KBVZh(cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47));
        entity.setLl_KBVZh(cursor.isNull(offset + 48) ? null : cursor.getString(offset + 48));
        entity.setJw_KBVZh(cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49));
        entity.setEyht_KBVZh(cursor.isNull(offset + 50) ? null : cursor.getString(offset + 50));
        entity.setYyht_KBVZh(cursor.isNull(offset + 51) ? null : cursor.getString(offset + 51));
        entity.setYq_KBVZh(cursor.isNull(offset + 52) ? null : cursor.getString(offset + 52));
        entity.setQtwd_KBVZh(cursor.isNull(offset + 53) ? null : cursor.getString(offset + 53));
        entity.setLlQGDTJ_KBVZh(cursor.isNull(offset + 54) ? null : cursor.getString(offset + 54));
        entity.setLlBGDTJ_KBVZh(cursor.isNull(offset + 55) ? null : cursor.getString(offset + 55));
        entity.setZglBGDTJ_KBVZh(cursor.isNull(offset + 56) ? null : cursor.getString(offset + 56));
        entity.setJxzkdBGDTJ_KBVZh(cursor.isNull(offset + 57) ? null : cursor.getString(offset + 57));
        entity.setEyht_ZHGL(cursor.isNull(offset + 58) ? null : cursor.getString(offset + 58));
        entity.setYyht_ZHGL(cursor.isNull(offset + 59) ? null : cursor.getString(offset + 59));
        entity.setYq_ZHGL(cursor.isNull(offset + 60) ? null : cursor.getString(offset + 60));
        entity.setJw_ZHGL(cursor.isNull(offset + 61) ? null : cursor.getString(offset + 61));
        entity.setGdfy_ZHGL(cursor.isNull(offset + 62) ? null : cursor.getString(offset + 62));
        entity.setGdjy_ZHGL(cursor.isNull(offset + 63) ? null : cursor.getString(offset + 63));
        entity.setGdcy_ZHGL(cursor.isNull(offset + 64) ? null : cursor.getString(offset + 64));
        entity.setLl_ZHGL(cursor.isNull(offset + 65) ? null : cursor.getString(offset + 65));
        entity.setQtwd_ZHGL(cursor.isNull(offset + 66) ? null : cursor.getString(offset + 66));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TaskResEnity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TaskResEnity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TaskResEnity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
